In [1]:
import pandas as pd
import numpy as np
from caits.dataset._dataset2 import DatasetArray

## DatasetArray test

In [2]:
data = pd.read_csv('../examples/data/AirQuality.csv', sep=';', decimal=',')
data

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10/03/2004  18.00.00     2.6       1360.0     150.0      11.9   
1     10/03/2004  19.00.00     2.0       1292.0     112.0       9.4   
2     10/03/2004  20.00.00     2.2       1402.0      88.0       9.0   
3     10/03/2004  21.00.00     2.2       1376.0      80.0       9.2   
4     10/03/2004  22.00.00     1.6       1272.0      51.0       6.5   
...          ...       ...     ...          ...       ...       ...   
9466         NaN       NaN     NaN          NaN       NaN       NaN   
9467         NaN       NaN     NaN          NaN       NaN       NaN   
9468         NaN       NaN     NaN          NaN       NaN       NaN   
9469         NaN       NaN     NaN          NaN       NaN       NaN   
9470         NaN       NaN     NaN          NaN       NaN       NaN   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9466            NaN      NaN           NaN      NaN           NaN   
9467            NaN      NaN           NaN      NaN           NaN   
9468            NaN      NaN           NaN      NaN           NaN   
9469            NaN      NaN           NaN      NaN           NaN   
9470            NaN      NaN           NaN      NaN           NaN   

      PT08.S5(O3)     T    RH      AH  Unnamed: 15  Unnamed: 16  
0          1268.0  13.6  48.9  0.7578          NaN          NaN  
1           972.0  13.3  47.7  0.7255          NaN          NaN  
2          1074.0  11.9  54.0  0.7502          NaN          NaN  
3          1203.0  11.0  60.0  0.7867          NaN          NaN  
4          1110.0  11.2  59.6  0.7888          NaN          NaN  
...           ...   ...   ...     ...          ...          ...  
9466          NaN   NaN   NaN     NaN          NaN          NaN  
9467          NaN   NaN   NaN     NaN          NaN          NaN  
9468          NaN   NaN   NaN     NaN          NaN          NaN  
9469          NaN   NaN   NaN     NaN          NaN          NaN  
9470          NaN   NaN   NaN     NaN          NaN          NaN  

[9471 rows x 17 columns]

In [3]:
columns = list(data.columns)
columns

['Date',
 'Time',
 'CO(GT)',
 'PT08.S1(CO)',
 'NMHC(GT)',
 'C6H6(GT)',
 'PT08.S2(NMHC)',
 'NOx(GT)',
 'PT08.S3(NOx)',
 'NO2(GT)',
 'PT08.S4(NO2)',
 'PT08.S5(O3)',
 'T',
 'RH',
 'AH',
 'Unnamed: 15',
 'Unnamed: 16']

In [4]:
values = data.values
values


array([['10/03/2004', '18.00.00', 2.6, ..., 0.7578, nan, nan],
       ['10/03/2004', '19.00.00', 2.0, ..., 0.7255, nan, nan],
       ['10/03/2004', '20.00.00', 2.2, ..., 0.7502, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [5]:
dataset_obj = DatasetArray(X=values, cols_X=columns)
dataset_obj

Dataset object with 9471 items.

In [6]:
len(dataset_obj)

9471

In [7]:
dataset_obj.cols_X

{'Date': 0,
 'Time': 1,
 'CO(GT)': 2,
 'PT08.S1(CO)': 3,
 'NMHC(GT)': 4,
 'C6H6(GT)': 5,
 'PT08.S2(NMHC)': 6,
 'NOx(GT)': 7,
 'PT08.S3(NOx)': 8,
 'NO2(GT)': 9,
 'PT08.S4(NO2)': 10,
 'PT08.S5(O3)': 11,
 'T': 12,
 'RH': 13,
 'AH': 14,
 'Unnamed: 15': 15,
 'Unnamed: 16': 16}

In [8]:
dataset_obj.cols_y

{'y_Channel_0': 0}

In [9]:
dataset_obj[1]

(array(['10/03/2004', '19.00.00', 2.0, 1292.0, 112.0, 9.4, 955.0, 103.0,
        1174.0, 92.0, 1559.0, 972.0, 13.3, 47.7, 0.7255, nan, nan],
       dtype=object),
 array([None], dtype=object))

In [10]:
dataset_obj["T"]

array([13.6, 13.3, 11.9, ..., nan, nan, nan], dtype=object)

In [11]:
dataset_obj[1:4]

(array([['10/03/2004', '19.00.00', 2.0, 1292.0, 112.0, 9.4, 955.0, 103.0,
         1174.0, 92.0, 1559.0, 972.0, 13.3, 47.7, 0.7255, nan, nan],
        ['10/03/2004', '20.00.00', 2.2, 1402.0, 88.0, 9.0, 939.0, 131.0,
         1140.0, 114.0, 1555.0, 1074.0, 11.9, 54.0, 0.7502, nan, nan],
        ['10/03/2004', '21.00.00', 2.2, 1376.0, 80.0, 9.2, 948.0, 172.0,
         1092.0, 122.0, 1584.0, 1203.0, 11.0, 60.0, 0.7867, nan, nan]],
       dtype=object),
 array([[None],
        [None],
        [None]], dtype=object))

In [12]:
dataset_obj[1, "RH"], dataset_obj[1, "y_Channel_0"]

(47.7, None)

In [13]:
dataset_obj[1:4, "RH"], dataset_obj[1:4, "y_Channel_0"]

(array([47.7, 54.0, 60.0], dtype=object),
 array([None, None, None], dtype=object))

In [14]:
dataset_obj[1, ["RH", "T", "y_Channel_0"]]

(array([13.3, 47.7], dtype=object), array([None], dtype=object))

In [15]:
dataset_obj[1:5, ["RH", "T", "y_Channel_0"]]

In [16]:
dataset_obj[[1,5], [2,4]]

array([2.0, 38.0], dtype=object)

In [17]:
dataset_obj[[1,5,6], ["T", "RH", "y_Channel_0"]]

(array([13.6, 47.7], dtype=object), array([None], dtype=object))

In [18]:
print(dataset_obj)

Dataset object with 9471 items.


In [19]:
count = 0
for row in dataset_obj:
    count += 1
count
    # print(row)

9471

In [20]:
dataset_obj.to_dict()

{'X': {'Date': array(['10/03/2004', '10/03/2004', '10/03/2004', ..., nan, nan, nan],
        dtype=object),
  'Time': array(['18.00.00', '19.00.00', '20.00.00', ..., nan, nan, nan],
        dtype=object),
  'CO(GT)': array([2.6, 2.0, 2.2, ..., nan, nan, nan], dtype=object),
  'PT08.S1(CO)': array([1360.0, 1292.0, 1402.0, ..., nan, nan, nan], dtype=object),
  'NMHC(GT)': array([150.0, 112.0, 88.0, ..., nan, nan, nan], dtype=object),
  'C6H6(GT)': array([11.9, 9.4, 9.0, ..., nan, nan, nan], dtype=object),
  'PT08.S2(NMHC)': array([1046.0, 955.0, 939.0, ..., nan, nan, nan], dtype=object),
  'NOx(GT)': array([166.0, 103.0, 131.0, ..., nan, nan, nan], dtype=object),
  'PT08.S3(NOx)': array([1056.0, 1174.0, 1140.0, ..., nan, nan, nan], dtype=object),
  'NO2(GT)': array([113.0, 92.0, 114.0, ..., nan, nan, nan], dtype=object),
  'PT08.S4(NO2)': array([1692.0, 1559.0, 1555.0, ..., nan, nan, nan], dtype=object),
  'PT08.S5(O3)': array([1268.0, 972.0, 1074.0, ..., nan, nan, nan], dtype=object),
 

In [21]:
dataset_obj.to_df()

{'X':             Date      Time CO(GT) PT08.S1(CO) NMHC(GT) C6H6(GT) PT08.S2(NMHC)  \
 0     10/03/2004  18.00.00    2.6      1360.0    150.0     11.9        1046.0   
 1     10/03/2004  19.00.00    2.0      1292.0    112.0      9.4         955.0   
 2     10/03/2004  20.00.00    2.2      1402.0     88.0      9.0         939.0   
 3     10/03/2004  21.00.00    2.2      1376.0     80.0      9.2         948.0   
 4     10/03/2004  22.00.00    1.6      1272.0     51.0      6.5         836.0   
 ...          ...       ...    ...         ...      ...      ...           ...   
 9466         NaN       NaN    NaN         NaN      NaN      NaN           NaN   
 9467         NaN       NaN    NaN         NaN      NaN      NaN           NaN   
 9468         NaN       NaN    NaN         NaN      NaN      NaN           NaN   
 9469         NaN       NaN    NaN         NaN      NaN      NaN           NaN   
 9470         NaN       NaN    NaN         NaN      NaN      NaN           NaN   
 
      NOx

In [22]:
for i, batch in enumerate(dataset_obj.batch(100)):
    print(f"----------------------- BATCH {i} -----------------------")
    print(batch)

----------------------- BATCH 0 -----------------------
(array([['10/03/2004', '18.00.00', 2.6, ..., 0.7578, nan, nan],
       ['10/03/2004', '19.00.00', 2.0, ..., 0.7255, nan, nan],
       ['10/03/2004', '20.00.00', 2.2, ..., 0.7502, nan, nan],
       ...,
       ['14/03/2004', '19.00.00', 4.6, ..., 0.8732, nan, nan],
       ['14/03/2004', '20.00.00', 5.9, ..., 0.921, nan, nan],
       ['14/03/2004', '21.00.00', 3.4, ..., 0.932, nan, nan]],
      dtype=object), array([[None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [None],
       [

In [23]:
train_data, test_data = dataset_obj.train_test_split(test_size=0.2)

In [24]:
train_data

Dataset object with 7576 items.

In [25]:
test_data

Dataset object with 1895 items.

In [26]:
train_data, test_data = dataset_obj.train_test_split(test_size=0.2, random_state=42)

In [27]:
train_data

Dataset object with 7576 items.

In [28]:
test_data

Dataset object with 1895 items.

In [29]:
new_data = train_data.unify(test_data)
new_data

Dataset object with 9471 items.

In [30]:
train_data + test_data


Dataset object with 9471 items.