# Multi-Axis statistical analysis test

In this notebook, we will create some trivial multi-axis data to check if the various statistical analysis functions work as expected.

## Step 1: Import libraries

In [28]:
import pandas as pd
import numpy as np
from caits.fe import (
    std_value,
    variance_value,
    mean_value,
    median_value,
    max_value,
    min_value,
    kurtosis_value,
    sample_skewness,
    signal_length,
    central_moments,
    rms_value,
    rms_max,
    rms_mean,
    rms_min,
    zcr_value,
    zcr_max,
    zcr_mean,
    zcr_min,
    energy,
    average_power,
    crest_factor,
    dominant_frequency,
    mfcc_mean,
    signal_stats
)

## Step 2: Initialize data

In [29]:
data = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [3, 30, 300],
    [4, 40, 400],
    [5, 50, 500],
    [6, 60, 600],
    [7, 70, 700],
    [8, 80, 800],
    [9, 90, 900],
    [10, 100, 1000],
])

data.shape

(10, 3)

## Step 3: Calculate basic statistics

In [30]:
means = mean_value(data)
means

array([  5.5,  55. , 550. ])

In [31]:
stds = std_value(data, ddof=1)
stds

array([  3.02765035,  30.27650354, 302.76503541])

In [32]:
variances = variance_value(data, ddof=1)
variances

array([9.16666667e+00, 9.16666667e+02, 9.16666667e+04])

In [33]:
medians = median_value(data)
medians

array([  5.5,  55. , 550. ])

In [34]:
maxs = max_value(data)
maxs

array([  10,  100, 1000])

In [35]:
mins = min_value(data)
mins

array([  1,  10, 100])

In [36]:
kurts = kurtosis_value(data)
kurts

array([-1.22424242, -1.22424242, -1.22424242])

In [37]:
skews = sample_skewness(data)
skews

array([0., 0., 0.])

In [38]:
centrals = central_moments(data)
centrals

array([[1.000000e+00, 1.000000e+00, 1.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00],
       [8.250000e+00, 8.250000e+02, 8.250000e+04],
       [0.000000e+00, 0.000000e+00, 0.000000e+00],
       [1.208625e+02, 1.208625e+06, 1.208625e+10]])

In [39]:
lengths = signal_length(data, 1, axis=0, time_mode="samples")
lengths

10

# Signal Statistics tests for multi-axis data

## Step 1: Initialize data

In [40]:
fs = 50000  # Sampling frequency in Hz
t = np.linspace(0, 1, fs, endpoint=False)  # 1 second of data

# Channel 0: Constant signal
ch0 = np.ones_like(t)

# Channel 1: Square wave (alternating ±1)
ch1 = np.sign(np.sin(2 * np.pi * 5 * t))  # 5 Hz square wave

# Channel 2: 1 Hz sine wave
ch2 = np.sin(2 * np.pi * 1 * t)

# Stack into (samples, channels) shape
data = np.stack([ch0, ch1, ch2], axis=1)  # shape (100, 3)

data.shape

(50000, 3)

## Step 2: Calculate statistics

In [41]:
rms_vals = rms_value(data)
rms_vals

array([1.        , 0.99999   , 0.70710678])

In [42]:
rms_maxs = rms_max(data, frame_length=3, hop_length=1)
rms_maxs

array([1.        , 1.        , 0.99999999])

In [43]:
rms_mins = rms_min(data, frame_length=3, hop_length=1)
rms_mins

array([8.16496581e-01, 5.77350269e-01, 7.25519744e-05])

In [44]:
rms_means = rms_mean(data, frame_length=3, hop_length=1)
rms_means

array([0.99999266, 0.99998421, 0.6366198 ])

In [45]:
zcr_vals = zcr_value(data)
zcr_vals

array([0.000000e+00, 1.800036e-04, 2.000040e-05])

In [46]:
zcr_maxs = zcr_max(data, frame_length=3, hop_length=1)
zcr_maxs

array([0.        , 0.33333333, 0.33333333])

In [47]:
zcr_means = zcr_mean(data, frame_length=3, hop_length=1)
zcr_means

array([0.00000000e+00, 1.20000000e-04, 1.33333333e-05])

In [48]:
zcr_mins = zcr_min(data, frame_length=3, hop_length=1)
zcr_mins

array([0., 0., 0.])

In [49]:
energies = energy(data)
energies

array([50000., 49999., 25000.])

In [50]:
average_powers = average_power(data)
average_powers

array([1.     , 0.99998, 0.5    ])

In [51]:
crest_factors = crest_factor(data)
crest_factors

array([1.        , 1.00001   , 1.41421356])

In [52]:
dominant_frequencies = dominant_frequency(data, fs=fs)
dominant_frequencies

array([0., 5., 1.])

In [53]:
mfcc_means = mfcc_mean(data, n_mfcc=10)
print(mfcc_means.shape)
mfcc_means

(10, 98)


array([[-168.66605624, -214.11438463, -426.39247536, -426.31279088,
        -426.25749038, -426.21945281, -426.19451709, -426.18026026,
        -385.51010453, -287.57387439, -276.06583599, -312.05166418,
        -426.22542543, -426.24383561, -426.26885675, -426.3010688 ,
        -426.34135644, -426.39103156, -341.95658932, -281.1782499 ,
        -279.9038437 , -334.21655997, -426.76692836, -426.88691808,
        -427.03371524, -427.03380593, -426.86218467, -426.75094702,
        -317.42626599, -277.15613836, -285.82105593, -370.94992396,
        -426.3817511 , -426.33380705, -426.2949868 , -426.264064  ,
        -426.24021317, -426.22289876, -301.0051399 , -275.04099099,
        -294.46768042, -425.42226897, -426.18202208, -426.19799103,
        -426.22497015, -426.26561383, -426.32449748, -401.03361419,
        -290.23919126, -275.94921321, -307.90670282, -426.37662792,
        -426.30179554, -426.24986975, -426.21431856, -426.19135636,
        -426.17877011, -350.35905066, -282.29910

In [54]:
stats = signal_stats(data, fs=fs, name="data", time_mode="samples")
stats

/home/kirk/PycharmProjects/crossai-ts/caits/fe/_statistical.py:130: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return kurtosis(array, axis=axis)
/home/kirk/PycharmProjects/crossai-ts/caits/fe/_statistical.py:158: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return skew(array, axis=axis, bias=False)


{'data_max': array([1., 1., 1.]),
 'data_min': array([ 1., -1., -1.]),
 'data_mean': array([ 1.0000000e+00, -2.0000000e-05,  3.1004272e-17]),
 'data_median': array([ 1.000000e+00, -5.000000e-01,  6.123234e-17]),
 'data_std': array([0.        , 0.99999   , 0.70710678]),
 'data_var': array([0.     , 0.99998, 0.5    ]),
 'data_kurtosis': array([     nan, -1.99998, -1.5    ]),
 'data_skewness': array([            nan,  4.00012000e-05, -1.15168401e-17]),
 'data_rms': array([1.        , 0.99999   , 0.70710678]),
 'data_dominant_frequency': array([0., 5., 1.]),
 'data_crest_factor': array([1.        , 1.00001   , 1.41421356]),
 'data_signal_length': 50000}

# Final Remarks

It seems that for most statistics it works fine.