# Multi-Axis statistical analysis test

In this notebook, we will create some trivial multi-axis data to check if the various statistical analysis functions work as expected.

## Step 1: Import libraries

In [42]:
import pandas as pd
import numpy as np
from caits.fe import (
    std_value,
    variance_value,
    mean_value,
    median_value,
    max_value,
    min_value,
    kurtosis_value,
    sample_skewness,
    signal_length,
    central_moments,
    rms_value,
    rms_max,
    rms_mean,
    rms_min,
    zcr_value,
    zcr_max,
    zcr_mean,
    zcr_min,
    energy,
    average_power,
    crest_factor,
    dominant_frequency,
    mfcc_mean,
    signal_stats
)

## Step 2: Initialize data

In [2]:
data = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [3, 30, 300],
    [4, 40, 400],
    [5, 50, 500],
    [6, 60, 600],
    [7, 70, 700],
    [8, 80, 800],
    [9, 90, 900],
    [10, 100, 1000],
])

data.shape

(10, 3)

## Step 3: Calculate basic statistics

In [3]:
means = mean_value(data)
means

array([  5.5,  55. , 550. ])

In [4]:
stds = std_value(data, ddof=1)
stds

array([  3.02765035,  30.27650354, 302.76503541])

In [5]:
variances = variance_value(data, ddof=1)
variances

array([9.16666667e+00, 9.16666667e+02, 9.16666667e+04])

In [6]:
medians = median_value(data)
medians

array([  5.5,  55. , 550. ])

In [7]:
maxs = max_value(data)
maxs

array([  10,  100, 1000])

In [8]:
mins = min_value(data)
mins

array([  1,  10, 100])

In [9]:
kurts = kurtosis_value(data)
kurts

array([-1.22424242, -1.22424242, -1.22424242])

In [10]:
skews = sample_skewness(data)
skews

array([0., 0., 0.])

In [15]:
centrals = central_moments(data)
centrals

array([[1.000000e+00, 1.000000e+00, 1.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00],
       [8.250000e+00, 8.250000e+02, 8.250000e+04],
       [0.000000e+00, 0.000000e+00, 0.000000e+00],
       [1.208625e+02, 1.208625e+06, 1.208625e+10]])

In [18]:
lengths = signal_length(data, 1, axis=0, time_mode="samples")
lengths

10

# Signal Statistics tests for multi-axis data

## Step 1: Initialize data

In [20]:
fs = 100  # Sampling frequency in Hz
t = np.linspace(0, 1, fs, endpoint=False)  # 1 second of data

# Channel 0: Constant signal
ch0 = np.ones_like(t)

# Channel 1: Square wave (alternating ±1)
ch1 = np.sign(np.sin(2 * np.pi * 5 * t))  # 5 Hz square wave

# Channel 2: 1 Hz sine wave
ch2 = np.sin(2 * np.pi * 1 * t)

# Stack into (samples, channels) shape
data = np.stack([ch0, ch1, ch2], axis=1)  # shape (100, 3)

data.shape

(100, 3)

## Step 2: Calculate statistics

In [24]:
rms_vals = rms_value(data)
rms_vals

array([1.        , 0.99498744, 0.70710678])

In [25]:
rms_maxs = rms_max(data, frame_length=3, hop_length=1)
rms_maxs

0.7742572656559091

In [26]:
rms_mins = rms_min(data, frame_length=3, hop_length=1)
rms_mins

0.4475073667432944

In [27]:
rms_means = rms_mean(data, frame_length=3, hop_length=1)
rms_means

0.701779076891624

In [29]:
zcr_vals = zcr_value(data)
zcr_vals

array([0.        , 0.09090909, 0.01010101])

In [30]:
zcr_maxs = zcr_max(data, frame_length=3, hop_length=1)
zcr_maxs

array([0.        , 0.        , 0.33333333, 0.33333333, 0.33333333])

In [31]:
zcr_means = zcr_mean(data, frame_length=3, hop_length=1)
zcr_means

array([0.        , 0.        , 0.06      , 0.00666667, 0.00666667])

In [32]:
zcr_mins = zcr_min(data, frame_length=3, hop_length=1)
zcr_mins

array([0., 0., 0., 0., 0.])

In [33]:
energies = energy(data)
energies

array([100.,  99.,  50.])

In [34]:
average_powers = average_power(data)
average_powers

array([1.  , 0.99, 0.5 ])

In [40]:
crest_factors = crest_factor(data)
crest_factors

array([1.        , 1.00503782, 1.41421356])

In [37]:
dominant_frequencies = dominant_frequency(data, fs=fs)
dominant_frequencies

array([0., 5., 1.])

In [39]:
mfcc_means = mfcc_mean(data, n_mfcc=10)
mfcc_means

array([[-64.0188615 ],
       [117.72362371],
       [ 19.43709224],
       [ 10.59663048],
       [  1.71417742],
       [ 11.61308284],
       [ 17.81894305],
       [  8.51998583],
       [ -1.72845882],
       [  0.41813162]])

In [45]:
stats = signal_stats(data, fs=fs, name="data", time_mode="samples")
stats

{'data_max': array([1., 1., 1.]),
 'data_min': array([ 1., -1., -1.]),
 'data_mean': array([ 1.00000000e+00, -1.00000000e-02,  7.67441666e-17]),
 'data_median': array([ 1.000000e+00, -5.000000e-01,  6.123234e-17]),
 'data_std': array([0.        , 0.99493718, 0.70710678]),
 'data_var': array([0.    , 0.9899, 0.5   ]),
 'data_kurtosis': array([        nan, -1.98949695, -1.5       ]),
 'data_skewness': array([            nan,  2.03061069e-02, -4.74196231e-16]),
 'data_rms': array([1.        , 0.99498744, 0.70710678]),
 'data_dominant_frequency': array([0., 5., 1.]),
 'data_crest_factor': array([1.        , 1.00503782, 1.41421356]),
 'data_signal_length': 100}

# Final Remarks

It seems that for most statistics it works fine.